Repository Fast-64/fast64, pull requests merged in 2022-10, with the labels that each got.

#121 fixed exporting with modifiers that rely on other objects
  fast64_internal/utility.py
Labels: waiting for author

#154 [OoT] Minor room behavior improvements
  fast64_internal/oot/oot_constants.py
  fast64_internal/oot/oot_level_writer.py
  fast64_internal/oot/oot_scene_room.py
Labels: merge soon, oot

#150 [OoT] Imports cleanup
  __init__.py
  fast64_internal/__init__.py
  fast64_internal/oot/__init__.py
  fast64_internal/oot/c_writer/oot_level_c.py
  fast64_internal/oot/c_writer/oot_scene_bootup.py
  fast64_internal/oot/c_writer/oot_scene_folder.py
  fast64_internal/oot/c_writer/oot_scene_table_c.py
  fast64_internal/oot/c_writer/oot_spec.py
  fast64_internal/oot/oot_actor.py
  fast64_internal/oot/oot_anim.py
  fast64_internal/oot/oot_collision.py
  fast64_internal/oot/oot_collision_classes.py
  fast64_internal/oot/oot_cutscene.py
  fast64_internal/oot/oot_f3d_writer.py
  fast64_internal/oot/oot_level.py
  fast64_internal/oot/oot_level_classes.py
  fast64_internal/oot/oot_level_writer.py
  fast64_internal/oot/oot_model_classes.py
  fast64_internal/oot/oot_operators.py
  fast64_internal/oot/oot_scene_room.py
  fast64_internal/oot/oot_skeleton.py
  fast64_internal/oot/oot_spline.py
  fast64_internal/oot/oot_utility.py
  fast64_internal/sm64/sm64_geolayout_constants.py
  fast64_internal/sm64/sm64_level_parser.py
  fast64_internal/sm64/sm64_rom_tweaks.py
Labels: merge soon, codebase

#153 [OoT] Format what's left (3 exceptions)
  fast64_internal/oot/c_writer/oot_scene_folder.py
  fast64_internal/oot/c_writer/oot_spec.py
  fast64_internal/oot/oot_cutscene.py
  fast64_internal/oot/oot_spline.py
Labels: merge soon, codebase

#157 [SM64] allow user to export a level from any of its children
  fast64_internal/sm64/sm64_level_writer.py
Labels: merge soon, sm64

#158 [Performance] mute unused texture nodes
  fast64_internal/f3d/f3d_material.py
Labels: enhancement, merge soon

#162 [SM64] Applied black (3 exceptions)
  fast64_internal/sm64/sm64_anim.py
  fast64_internal/sm64/sm64_camera.py
  fast64_internal/sm64/sm64_collision.py
  fast64_internal/sm64/sm64_constants.py
  fast64_internal/sm64/sm64_enum_parser.py
  fast64_internal/sm64/sm64_f3d_parser.py
  fast64_internal/sm64/sm64_function_map.py
  fast64_internal/sm64/sm64_geolayout_bone.py
  fast64_internal/sm64/sm64_geolayout_classes.py
  fast64_internal/sm64/sm64_geolayout_constants.py
  fast64_internal/sm64/sm64_geolayout_parser.py
  fast64_internal/sm64/sm64_geolayout_utility.py
  fast64_internal/sm64/sm64_level_constants.py
  fast64_internal/sm64/sm64_level_parser.py
  fast64_internal/sm64/sm64_rom_tweaks.py
  fast64_internal/sm64/sm64_spline.py
  fast64_internal/sm64/sm64_texscroll.py
Labels: merge soon, codebase
