Repository Fast-64/fast64, pull requests merged in 2023-01, with the labels that each got.

#202 Fix missing import
  fast64_internal/utility_anim.py
Labels: bug, merge soon

#207 [bugfix] SM64 mat override fixes
  fast64_internal/sm64/sm64_geolayout_writer.py
Labels: merge soon

#204 [OoT] Applied new organisation to cutscene and skeleton
  fast64_internal/oot/cutscene/constants.py
  fast64_internal/oot/cutscene/exporter/__init__.py
  fast64_internal/oot/cutscene/exporter/classes.py
  fast64_internal/oot/cutscene/exporter/functions.py
  fast64_internal/oot/cutscene/operators.py
  fast64_internal/oot/cutscene/properties.py
  fast64_internal/oot/oot_anim.py
  fast64_internal/oot/oot_constants.py
  fast64_internal/oot/oot_cutscene.py
  fast64_internal/oot/oot_level_classes.py
  fast64_internal/oot/oot_level_writer.py
  fast64_internal/oot/oot_skeleton.py
  fast64_internal/oot/scene/exporter/to_c/__init__.py
  fast64_internal/oot/scene/exporter/to_c/scene_cutscene.py
  fast64_internal/oot/scene/properties.py
  fast64_internal/oot/skeleton/constants.py
  fast64_internal/oot/skeleton/exporter/__init__.py
  fast64_internal/oot/skeleton/exporter/classes.py
  fast64_internal/oot/skeleton/exporter/functions.py
  fast64_internal/oot/skeleton/importer/__init__.py
  fast64_internal/oot/skeleton/importer/functions.py
  fast64_internal/oot/skeleton/operators.py
  fast64_internal/oot/skeleton/properties.py
  fast64_internal/oot/skeleton/utility.py
Labels: merge soon

#195 Added Gfx tag system + Split vertex/tile scrolling
  fast64_internal/f3d/f3d_gbi.py
  fast64_internal/f3d/f3d_writer.py
  fast64_internal/oot/oot_model_classes.py
  fast64_internal/sm64/sm64_f3d_writer.py
  fast64_internal/sm64/sm64_geolayout_writer.py
  fast64_internal/sm64/sm64_level_writer.py
  fast64_internal/sm64/sm64_texscroll.py
  fast64_internal/utility.py
Labels: codebase, f3d

#211 [OoT] Fixed 4 issues
  fast64_internal/oot/cutscene/properties.py
  fast64_internal/oot/oot_collision.py
  fast64_internal/oot/scene/exporter/to_c/scene_header.py
  fast64_internal/oot/scene/exporter/to_c/spec.py
Labels: merge soon

#201 Fix export hidden with collections
  fast64_internal/oot/collision/operators.py
  fast64_internal/oot/oot_level_writer.py
  fast64_internal/sm64/sm64_level_writer.py
  fast64_internal/utility.py
Labels: bug
