Repository Fast-64/fast64, pull requests merged in 2023-05, with the labels that each got.

#228 Fix a mistake from a previous PR, and workaround for a Blender 3.5 bug related to uvs
  fast64_internal/f3d/f3d_parser.py
  fast64_internal/f3d/flipbook.py
Labels: bug

#229 [bugfix] DPSetAlphaCompare Binary Export Fix
  fast64_internal/f3d/f3d_gbi.py
Labels: bug, merge soon

#222 [SM64] Mat override fixes
  fast64_internal/sm64/sm64_geolayout_writer.py
Labels: bug, sm64
