Repository Fast-64/fast64, pull requests merged in 2024-07, with the labels that each got.

#367 [F3D] Homebrew Mode Improvements
  fast64_internal/f3d/f3d_material.py
  fast64_internal/f3d/f3d_material_presets.py
  fast64_internal/f3d/f3d_writer.py
  fast64_internal/sm64/sm64_geolayout_bone.py
Labels: merge soon

#280 [SM64] Settings Rework
  __init__.py
  fast64_internal/f3d/f3d_gbi.py
  fast64_internal/f3d/f3d_material.py
  fast64_internal/f3d/f3d_parser.py
  fast64_internal/f3d/f3d_writer.py
  fast64_internal/operators.py
  fast64_internal/panels.py
  fast64_internal/repo_settings.py
  fast64_internal/sm64/README.md
  fast64_internal/sm64/__init__.py
  fast64_internal/sm64/settings/constants.py
  fast64_internal/sm64/settings/panels.py
  fast64_internal/sm64/settings/properties.py
  fast64_internal/sm64/settings/repo_settings.py
  fast64_internal/sm64/sm64_anim.py
  fast64_internal/sm64/sm64_collision.py
  fast64_internal/sm64/sm64_constants.py
  fast64_internal/sm64/sm64_f3d_parser.py
  fast64_internal/sm64/sm64_f3d_writer.py
  fast64_internal/sm64/sm64_geolayout_classes.py
  fast64_internal/sm64/sm64_geolayout_parser.py
  fast64_internal/sm64/sm64_geolayout_writer.py
  fast64_internal/sm64/sm64_level_writer.py
  fast64_internal/sm64/sm64_objects.py
  fast64_internal/sm64/sm64_texscroll.py
  fast64_internal/sm64/sm64_utility.py
  fast64_internal/sm64/tools/__init__.py
  fast64_internal/sm64/tools/operators.py
  fast64_internal/sm64/tools/panels.py
  fast64_internal/sm64/tools/properties.py
  fast64_internal/utility.py
Labels: enhancement, merge soon, sm64, codebase

#372 [SM64] Fix saveSkinnedMeshByMaterial
  fast64_internal/sm64/sm64_geolayout_writer.py
Labels: merge soon

#370 [F3D] Fix small issue with world defaults UI
  fast64_internal/f3d/f3d_material.py
Labels: review code please, f3d

#383 [Codebase] Small generalized upgrade function
  fast64_internal/f3d/f3d_material.py
  fast64_internal/f3d_material_converter.py
  fast64_internal/sm64/settings/properties.py
  fast64_internal/sm64/sm64_objects.py
  fast64_internal/sm64/tools/properties.py
  fast64_internal/utility.py
Labels: merge soon, codebase

#379 [F3D] Don´t hide properties that will get exported (specifically geo modes)
  fast64_internal/f3d/f3d_material.py
Labels: merge soon

#382 Improved nodes preview: F3DEX3 and OoT lighting
  __init__.py
  fast64_internal/f3d/f3d_material.py
  fast64_internal/f3d/f3d_material_library.blend
  fast64_internal/f3d_material_converter.py
  fast64_internal/oot/exporter/scene/general.py
  fast64_internal/oot/oot_level_parser.py
  fast64_internal/oot/scene/properties.py
  fast64_internal/render_settings.py
  fast64_internal/utility.py
Labels: merge soon

#395 [SM64] Fix usage of sm64 scale in animations
  fast64_internal/sm64/sm64_anim.py
Labels: merge soon

#394 [SM64] remove " after ultra64 include
  fast64_internal/sm64/sm64_level_writer.py
Labels: merge soon
