Repository Fast-64/fast64, pull requests merged in 2024-05, with the labels that each got.

#344 Fix OoT import failing in Blender 4.1
  fast64_internal/f3d/f3d_parser.py
Labels: merge soon

#345 Fixed bug with custom lights
  fast64_internal/utility.py
Labels: merge soon

#339 [SM64] Fix object rotations
  fast64_internal/sm64/sm64_objects.py
Labels: merge soon

#290 [OoT] Fix ``Cutscene Main`` obj empty type upgrade issues
  fast64_internal/oot/oot_upgrade.py
  fast64_internal/oot/props_panel_main.py
Labels: bug, merge soon, oot

#343 [OoT] Fix cutscene import issues
  fast64_internal/oot/cutscene/classes.py
  fast64_internal/oot/cutscene/importer/classes.py
Labels: bug, merge soon

#324 [SM64] Move into the new folders for settings rework
  __init__.py
  fast64_internal/panels.py
  fast64_internal/sm64/__init__.py
  fast64_internal/sm64/settings/__init__.py
  fast64_internal/sm64/settings/constants.py
  fast64_internal/sm64/settings/panels.py
  fast64_internal/sm64/settings/properties.py
  fast64_internal/sm64/sm64_constants.py
  fast64_internal/sm64/tools/__init__.py
  fast64_internal/sm64/tools/operators.py
  fast64_internal/sm64/tools/panels.py
  fast64_internal/utility.py
Labels: merge soon

#336 [SM64] Sort Level Objects Alphabetically
  fast64_internal/sm64/sm64_objects.py
Labels: merge soon
