Repository Fast-64/fast64, pull requests merged in 2024-01, with the labels that each got.

#274 Bump version to v2.2.0
  __init__.py
Labels: merge soon

#279 Cleanup: delete f3d_constants.py
  fast64_internal/f3d/f3d_constants.py
  fast64_internal/f3d/f3d_texture_writer.py
  fast64_internal/f3d/f3d_writer.py
  pyproject.toml
Labels: merge soon, codebase

#277 black format
  __init__.py
  fast64_internal/f3d/f3d_bleed.py
  fast64_internal/f3d/f3d_enums.py
  fast64_internal/f3d/f3d_gbi.py
  fast64_internal/f3d/f3d_generate_presets.py
  fast64_internal/f3d/f3d_material.py
  fast64_internal/f3d/f3d_render_engine.py
  fast64_internal/f3d/f3d_writer.py
  fast64_internal/f3d/flipbook.py
  fast64_internal/f3d_material_converter.py
  fast64_internal/panels.py
  fast64_internal/render_settings.py
  fast64_internal/sm64/c_templates/tile_scroll.py
  fast64_internal/sm64/parse_function_map.py
  fast64_internal/sm64/sm64_anim.py
  fast64_internal/sm64/sm64_collision.py
  fast64_internal/sm64/sm64_constants.py
  fast64_internal/sm64/sm64_geolayout_classes.py
  fast64_internal/sm64/sm64_geolayout_writer.py
  fast64_internal/sm64/sm64_objects.py
  fast64_internal/sm64/sm64_rom_tweaks.py
  fast64_internal/sm64/sm64_texscroll.py
  fast64_internal/sm64/sm64_utility.py
  fast64_internal/utility.py
  fast64_internal/utility_anim.py
  pyproject.toml
Labels: merge soon, codebase

#278 Black Lint with github actions
  .github/workflows/black-lint.yml
Labels: merge soon, codebase

#296 Removed tex1 related code from BSDF to F3D converter
  fast64_internal/f3d_material_converter.py
Labels: merge soon

#281 Name data in f3d_material_library.blend fast64-specific names
  fast64_internal/f3d/f3d_material.py
  fast64_internal/f3d/f3d_material_library.blend
Labels: merge soon, codebase

#285 [F3D] Material Ordered By Slot
  fast64_internal/f3d/f3d_writer.py
Labels: merge soon, f3d

#303 Use Black 23 specifically
  .github/workflows/black-lint.yml
  README.md
  pyproject.toml
Labels: codebase

#287 [OoT] Fixed door upgrade
  fast64_internal/oot/oot_upgrade.py
Labels: bug, merge soon, oot

#238 [OOT] Applied new organisation to ``oot_collision.py`` and ``oot_collision_classes.py``
  fast64_internal/oot/collision/constants.py
  fast64_internal/oot/collision/exporter/__init__.py
  fast64_internal/oot/collision/exporter/classes.py
  fast64_internal/oot/collision/exporter/functions.py
  fast64_internal/oot/collision/exporter/to_c/__init__.py
  fast64_internal/oot/collision/exporter/to_c/collision.py
  fast64_internal/oot/collision/operators.py
  fast64_internal/oot/collision/panels.py
  fast64_internal/oot/collision/properties.py
  fast64_internal/oot/oot_level_classes.py
  fast64_internal/oot/oot_level_parser.py
  fast64_internal/oot/oot_level_writer.py
  fast64_internal/oot/scene/exporter/to_c/scene_collision.py
  fast64_internal/oot/spline/properties.py
Labels: merge soon, oot, codebase

#237 [OOT] Applied new organisation to remaining code from ``oot_anim.py``
  fast64_internal/oot/animation/exporter/__init__.py
  fast64_internal/oot/animation/exporter/classes.py
  fast64_internal/oot/animation/exporter/functions.py
  fast64_internal/oot/animation/importer/__init__.py
  fast64_internal/oot/animation/importer/functions.py
  fast64_internal/oot/animation/operators.py
  fast64_internal/oot/oot_anim.py
Labels: merge soon, codebase
