Repository Fast-64/fast64, pull requests merged in 2025-08, with the labels that each got.

#571 Fixup 565 normal import
  fast64_internal/utility.py
Labels: bug, merge soon

#552 Fix Link import/export
  fast64_internal/z64/skeleton/importer/functions.py
  fast64_internal/z64/skeleton/utility.py
  fast64_internal/z64/texture_array.py
Labels: bug, merge soon, oot

#562 [OoT] Fix scene command issues
  fast64_internal/z64/exporter/scene/__init__.py
  fast64_internal/z64/exporter/scene/actors.py
  fast64_internal/z64/importer/actor.py
  fast64_internal/z64/importer/scene_header.py
Labels: bug, merge soon, oot

#569 [OoT] Fix cutscene export issues
  fast64_internal/z64/exporter/cutscene/__init__.py
Labels: bug, merge soon, oot

#568 Try to do append load post on register and remove it on unregister
  fast64_internal/f3d/f3d_material.py
Labels: merge soon, codebase

#570 Remove legacy & unused f3d_render_engine
  __init__.py
  fast64_internal/f3d/__init__.py
  fast64_internal/f3d/f3d_render_engine.py
Labels: merge soon, codebase

#512 [SM64] Bring more props to combined and merge level enums
  fast64_internal/sm64/settings/properties.py
  fast64_internal/sm64/sm64_anim.py
  fast64_internal/sm64/sm64_collision.py
  fast64_internal/sm64/sm64_constants.py
  fast64_internal/sm64/sm64_f3d_parser.py
  fast64_internal/sm64/sm64_f3d_writer.py
  fast64_internal/sm64/sm64_geolayout_parser.py
  fast64_internal/sm64/sm64_geolayout_writer.py
  fast64_internal/sm64/sm64_level_parser.py
  fast64_internal/sm64/tools/operators.py
  fast64_internal/sm64/tools/properties.py
  fast64_internal/utility.py
Labels: enhancement, merge soon, sm64

#531 [SM64] Add lighting engine presets
  fast64_internal/f3d/f3d_material.py
  fast64_internal/f3d/f3d_material_presets.py
  fast64_internal/sm64/settings/properties.py
Labels: enhancement, merge soon, sm64

#513 [SM64] Implement someone level template styled bounds
  fast64_internal/sm64/tools/operators.py
Labels: enhancement, merge soon, sm64

#565 [F3D + SM64] Dedup mesh names, fixes repeated final revert DLs
  fast64_internal/f3d/f3d_gbi.py
  fast64_internal/sm64/sm64_geolayout_writer.py
Labels: bug, sm64, f3d

#566 [F3D] Fix node creation in 4.5
  fast64_internal/f3d/f3d_material_helpers.py
Labels: merge soon

#457 [SM64] Custom level script and special commands and improvements to custom geo commands
  README.md
  __init__.py
  fast64_internal/f3d/f3d_parser.py
  fast64_internal/operators.py
  fast64_internal/repo_settings.py
  fast64_internal/sm64/README.md
  fast64_internal/sm64/__init__.py
  fast64_internal/sm64/animation/operators.py
  fast64_internal/sm64/animation/utility.py
  fast64_internal/sm64/custom_cmd/__init__.py
  fast64_internal/sm64/custom_cmd/exporting.py
  fast64_internal/sm64/custom_cmd/operators.py
  fast64_internal/sm64/custom_cmd/properties.py
  fast64_internal/sm64/custom_cmd/utility.py
  fast64_internal/sm64/settings/properties.py
  fast64_internal/sm64/sm64_collision.py
  fast64_internal/sm64/sm64_geolayout_bone.py
  fast64_internal/sm64/sm64_geolayout_classes.py
  fast64_internal/sm64/sm64_geolayout_parser.py
  fast64_internal/sm64/sm64_geolayout_utility.py
  fast64_internal/sm64/sm64_geolayout_writer.py
  fast64_internal/sm64/sm64_level_writer.py
  fast64_internal/sm64/sm64_objects.py
  fast64_internal/utility.py
Labels: enhancement, merge soon, sm64
